/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import entity.FoodAndDrink;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.util.HashMap;
import java.util.Set;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicTabbedPaneUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thinkpad E440
 */
public class OrderJframe extends javax.swing.JFrame {

    HashMap<FoodAndDrink, Integer> danhSachMonAn = new HashMap<>();
    DefaultTableModel modelTableDanhSachMonAn;

    /**
     * Creates new form Order
     */
    public OrderJframe() {
        initComponents();
        inItTab();
        inItTable();
        addBurgerPanel();

        setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTaoDon = new javax.swing.JButton();
        btnPotato = new javax.swing.JButton();
        btnCream = new javax.swing.JButton();
        btnBurger = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnDrink = new javax.swing.JButton();
        btnList = new javax.swing.JButton();
        btnLichSu = new javax.swing.JButton();
        tabbedTong = new javax.swing.JTabbedPane();
        tabTaoDonHang = new javax.swing.JPanel();
        tbpSub = new javax.swing.JTabbedPane();
        tabBurger = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelContainerBurger = new javax.swing.JPanel();
        tabPotato = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        panelContainerPotato = new javax.swing.JPanel();
        tabCream = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        panelContainerCream = new javax.swing.JPanel();
        tabDrink = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        panelContainerDrink = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDonHang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelTongTien = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TabListDonHang = new javax.swing.JPanel();
        tabLichSu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnTaoDon.setBackground(new java.awt.Color(255, 255, 255));
        btnTaoDon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTaoDon.setForeground(new java.awt.Color(0, 0, 0));
        btnTaoDon.setText("Tạo đơn hàng");
        btnTaoDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoDonActionPerformed(evt);
            }
        });

        btnPotato.setBackground(new java.awt.Color(255, 255, 255));
        btnPotato.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPotato.setForeground(new java.awt.Color(0, 0, 0));
        btnPotato.setIcon(new javax.swing.ImageIcon("E:\\Hoctap\\dev\\du An 1\\DuAn1\\src\\main\\resources\\image\\logoCream.png")); // NOI18N
        btnPotato.setText("Potato");
        btnPotato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotatoActionPerformed(evt);
            }
        });

        btnCream.setBackground(new java.awt.Color(255, 255, 255));
        btnCream.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCream.setForeground(new java.awt.Color(0, 0, 0));
        btnCream.setIcon(new javax.swing.ImageIcon("E:\\Hoctap\\dev\\du An 1\\DuAn1\\src\\main\\resources\\image\\logoDrink.png")); // NOI18N
        btnCream.setText("Ice Cream");
        btnCream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreamActionPerformed(evt);
            }
        });

        btnBurger.setBackground(new java.awt.Color(255, 255, 255));
        btnBurger.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBurger.setForeground(new java.awt.Color(0, 0, 0));
        btnBurger.setIcon(new javax.swing.ImageIcon("E:\\Hoctap\\dev\\du An 1\\DuAn1\\src\\main\\resources\\image\\logoPotato.png")); // NOI18N
        btnBurger.setText("Burger");
        btnBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBurgerActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo_brand.png"))); // NOI18N

        btnDrink.setBackground(new java.awt.Color(255, 255, 255));
        btnDrink.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDrink.setForeground(new java.awt.Color(0, 0, 0));
        btnDrink.setIcon(new javax.swing.ImageIcon("E:\\Hoctap\\dev\\du An 1\\DuAn1\\src\\main\\resources\\image\\logoDrink.png")); // NOI18N
        btnDrink.setText("Drink");
        btnDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkActionPerformed(evt);
            }
        });

        btnList.setBackground(new java.awt.Color(255, 255, 255));
        btnList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnList.setForeground(new java.awt.Color(0, 0, 0));
        btnList.setText("List đơn hàng");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        btnLichSu.setBackground(new java.awt.Color(255, 255, 255));
        btnLichSu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLichSu.setForeground(new java.awt.Color(0, 0, 0));
        btnLichSu.setText("Lịch sử đơn hàng");
        btnLichSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLichSuActionPerformed(evt);
            }
        });

        tabbedTong.setBackground(new java.awt.Color(153, 153, 255));

        tabTaoDonHang.setBackground(new java.awt.Color(255, 255, 255));

        tabBurger.setBackground(new java.awt.Color(255, 255, 255));
        tabBurger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(312, 1500));

        panelContainerBurger.setBackground(new java.awt.Color(255, 255, 255));
        panelContainerBurger.setName(""); // NOI18N
        panelContainerBurger.setPreferredSize(new java.awt.Dimension(300, 1500));
        panelContainerBurger.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jScrollPane1.setViewportView(panelContainerBurger);

        javax.swing.GroupLayout tabBurgerLayout = new javax.swing.GroupLayout(tabBurger);
        tabBurger.setLayout(tabBurgerLayout);
        tabBurgerLayout.setHorizontalGroup(
            tabBurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabBurgerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabBurgerLayout.setVerticalGroup(
            tabBurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabBurgerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpSub.addTab("tab1", tabBurger);

        tabPotato.setBackground(new java.awt.Color(153, 255, 153));

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setPreferredSize(new java.awt.Dimension(312, 1500));

        panelContainerPotato.setBackground(new java.awt.Color(255, 255, 255));
        panelContainerPotato.setName(""); // NOI18N
        panelContainerPotato.setPreferredSize(new java.awt.Dimension(300, 1500));
        panelContainerPotato.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jScrollPane3.setViewportView(panelContainerPotato);

        javax.swing.GroupLayout tabPotatoLayout = new javax.swing.GroupLayout(tabPotato);
        tabPotato.setLayout(tabPotatoLayout);
        tabPotatoLayout.setHorizontalGroup(
            tabPotatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPotatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabPotatoLayout.setVerticalGroup(
            tabPotatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPotatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpSub.addTab("tab3", tabPotato);

        tabCream.setBackground(new java.awt.Color(0, 204, 204));

        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setPreferredSize(new java.awt.Dimension(312, 1500));

        panelContainerCream.setBackground(new java.awt.Color(255, 255, 255));
        panelContainerCream.setName(""); // NOI18N
        panelContainerCream.setPreferredSize(new java.awt.Dimension(300, 1500));
        panelContainerCream.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jScrollPane4.setViewportView(panelContainerCream);

        javax.swing.GroupLayout tabCreamLayout = new javax.swing.GroupLayout(tabCream);
        tabCream.setLayout(tabCreamLayout);
        tabCreamLayout.setHorizontalGroup(
            tabCreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCreamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabCreamLayout.setVerticalGroup(
            tabCreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCreamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpSub.addTab("tab2", tabCream);

        tabDrink.setBackground(new java.awt.Color(0, 102, 255));

        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane5.setPreferredSize(new java.awt.Dimension(312, 1500));

        panelContainerDrink.setBackground(new java.awt.Color(255, 255, 255));
        panelContainerDrink.setName(""); // NOI18N
        panelContainerDrink.setPreferredSize(new java.awt.Dimension(300, 1500));
        panelContainerDrink.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jScrollPane5.setViewportView(panelContainerDrink);

        javax.swing.GroupLayout tabDrinkLayout = new javax.swing.GroupLayout(tabDrink);
        tabDrink.setLayout(tabDrinkLayout);
        tabDrinkLayout.setHorizontalGroup(
            tabDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabDrinkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabDrinkLayout.setVerticalGroup(
            tabDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabDrinkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpSub.addTab("tab4", tabDrink);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));

        tblDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên món", "Số lượng", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDonHang);
        if (tblDonHang.getColumnModel().getColumnCount() > 0) {
            tblDonHang.getColumnModel().getColumn(0).setPreferredWidth(150);
            tblDonHang.getColumnModel().getColumn(1).setPreferredWidth(60);
            tblDonHang.getColumnModel().getColumn(2).setPreferredWidth(90);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Bàn :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Danh Sách món :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Thành tiền :");

        labelTongTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTongTien.setText("1000000$");

        jButton1.setText("Chọn bàn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Tạo đơn hàng");

        jButton4.setText("Cập nhật");
        jButton4.setEnabled(false);

        jButton2.setText("Thanh toán");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jButton3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton4))))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelTongTien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabTaoDonHangLayout = new javax.swing.GroupLayout(tabTaoDonHang);
        tabTaoDonHang.setLayout(tabTaoDonHangLayout);
        tabTaoDonHangLayout.setHorizontalGroup(
            tabTaoDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTaoDonHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpSub, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabTaoDonHangLayout.setVerticalGroup(
            tabTaoDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabTaoDonHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabTaoDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbpSub))
                .addContainerGap())
        );

        tabbedTong.addTab("tab1", tabTaoDonHang);

        javax.swing.GroupLayout TabListDonHangLayout = new javax.swing.GroupLayout(TabListDonHang);
        TabListDonHang.setLayout(TabListDonHangLayout);
        TabListDonHangLayout.setHorizontalGroup(
            TabListDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
        );
        TabListDonHangLayout.setVerticalGroup(
            TabListDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        tabbedTong.addTab("tab2", TabListDonHang);

        javax.swing.GroupLayout tabLichSuLayout = new javax.swing.GroupLayout(tabLichSu);
        tabLichSu.setLayout(tabLichSuLayout);
        tabLichSuLayout.setHorizontalGroup(
            tabLichSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
        );
        tabLichSuLayout.setVerticalGroup(
            tabLichSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        tabbedTong.addTab("tab3", tabLichSu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDrink, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnBurger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPotato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCream, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnTaoDon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLichSu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedTong, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(tabbedTong, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTaoDon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPotato, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCream, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLichSu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLichSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLichSuActionPerformed
        // TODO add your handling code here:
        removeColorAllButton();
        removeColorAllButtonSub();
        blockOrder(true);
        checkClickButton(btnLichSu);
        tabbedTong.setSelectedIndex(2);
    }//GEN-LAST:event_btnLichSuActionPerformed

    private void btnCreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreamActionPerformed
        // TODO add your handling code here:
        removeColorAllButtonSub();
        checkClickButton(btnCream);
        tbpSub.setSelectedIndex(2);
    }//GEN-LAST:event_btnCreamActionPerformed

    private void btnDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkActionPerformed
        // TODO add your handling code here:
        removeColorAllButtonSub();
        checkClickButton(btnDrink);
        tbpSub.setSelectedIndex(3);
    }//GEN-LAST:event_btnDrinkActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        // TODO add your handling code here:
        removeColorAllButton();
        removeColorAllButtonSub();
        blockOrder(true);
        checkClickButton(btnList);
        tabbedTong.setSelectedIndex(1);
    }//GEN-LAST:event_btnListActionPerformed

    private void btnPotatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotatoActionPerformed
        // TODO add your handling code here:
        removeColorAllButtonSub();
        checkClickButton(btnPotato);
        tbpSub.setSelectedIndex(1);
    }//GEN-LAST:event_btnPotatoActionPerformed

    private void btnBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBurgerActionPerformed
        // TODO add your handling code here:

        removeColorAllButtonSub();
        checkClickButton(btnBurger);
        tbpSub.setSelectedIndex(0);
    }//GEN-LAST:event_btnBurgerActionPerformed

    private void btnTaoDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoDonActionPerformed
        // TODO add your handling code here:
        removeColorAllButton();
        checkClickButton(btnTaoDon);
        blockOrder(false);
        tabbedTong.setSelectedIndex(0);
    }//GEN-LAST:event_btnTaoDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderJframe().setVisible(true);
            }
        });
    }

    private void inItTab() {
        tabbedTong.setUI(new BasicTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int horizRunCount, int maxTabHeight) {
                return 0; // Set the tab area height to 0
            }
        });

        Color backgroundColor = new Color(255, 177, 55);
        btnTaoDon.setBackground(backgroundColor);
        tbpSub.setUI(new BasicTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int horizRunCount, int maxTabHeight) {
                return 0; // Set the tab area height to 0
            }
        });

    }

    private void inItTable() {
        modelTableDanhSachMonAn = (DefaultTableModel) tblDonHang.getModel();

    }

    private void fillTable() {
        modelTableDanhSachMonAn.setRowCount(0);
        Set<FoodAndDrink> key = danhSachMonAn.keySet();
        float tongTien = 0;
        for (FoodAndDrink f : key) {
            float gia = f.getGia() * danhSachMonAn.get(f);
            Object[] temp = {f.getTenThucAn(), gia, f.getGia()};
            modelTableDanhSachMonAn.addRow(temp);
            tongTien += gia;

        }
        labelTongTien.setText(tongTien + "$");

    }

    private void checkClickButton(JButton Button) {

        Color backgroundColor = new Color(255, 177, 55);
        Button.setBackground(backgroundColor);
    }

    private void removeColorAllButton() {
        btnTaoDon.setBackground(Color.white);
        btnList.setBackground(Color.white);
        btnLichSu.setBackground(Color.white);
    }

    private void removeColorAllButtonSub() {
        btnBurger.setBackground(Color.white);
        btnPotato.setBackground(Color.white);
        btnDrink.setBackground(Color.white);
        btnCream.setBackground(Color.white);
    }

    private void blockOrder(Boolean check) {
        btnBurger.setEnabled(!check);
        btnPotato.setEnabled(!check);
        btnCream.setEnabled(!check);
        btnDrink.setEnabled(!check);

    }

    private void addBurgerPanel() {
        FoodAndDrink n1 = new FoodAndDrink("Bg01", "Burger");
        FoodAndDrink n2 = new FoodAndDrink("Coca01", "cocacola");
        n1.setGia(1900);
        n2.setGia(9.00f);
        JPanel pn = ClonePanel(n1);
        JPanel pn2 = ClonePanel(n1);
        JPanel pn3 = ClonePanel(n2);
        panelContainerBurger.add(pn);
        panelContainerBurger.add(pn2);
        panelContainerBurger.add(pn3);
    }

    //  Tạo panel chứa sản phẩm bà nút add
    private JPanel ClonePanel(FoodAndDrink food) {

        JPanel panelReturn = new JPanel();
        FlowLayout layout = new FlowLayout();
        panelReturn.setLayout(layout);

        Dimension sizePanel = new Dimension(115, 150);
        panelReturn.setPreferredSize(sizePanel);

        Dimension sizeLabel = new Dimension(100, 100);
        JLabel label = new JLabel();
        label.setPreferredSize(sizeLabel);
        JButton btn = new JButton();

        AbstractAction ac = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (!danhSachMonAn.containsKey(food)) {
                    danhSachMonAn.put(food, 1);
                } else {
                    int soLuongCu = danhSachMonAn.get(food);
                    danhSachMonAn.replace(food, soLuongCu, soLuongCu + 1);

                }

                System.out.println(danhSachMonAn.toString());
                fillTable();
            }
        };

        btn.setAction(ac);
        btn.setText("Add");

        label.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\image\\burger_sandwich_1 2.png")); // NOI18N

        panelReturn.add(label);
        panelReturn.add(btn);

        return panelReturn;
    }

//    private JPanel ClonePanel() {
//
//        JPanel panelReturn = new JPanel();
//        FlowLayout layout = new FlowLayout();
//        panelReturn.setLayout(layout);
//
//        Dimension sizePanel = new Dimension(120, 150);
//        panelReturn.setPreferredSize(sizePanel);
//
//        Dimension sizeLabel = new Dimension(100, 100);
//        JLabel label = new JLabel();
//        label.setPreferredSize(sizeLabel);
//        JButton btn = new JButton();
//
//        AbstractAction ac = new AbstractAction() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//
//            }
//        };
//
//        btn.setAction(ac);
//        btn.setText("Add");
//
//        label.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\image\\burger_sandwich_1 2.png")); // NOI18N
//
//        panelReturn.add(label);
//        panelReturn.add(btn);
//
//        return panelReturn;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TabListDonHang;
    private javax.swing.JButton btnBurger;
    private javax.swing.JButton btnCream;
    private javax.swing.JButton btnDrink;
    private javax.swing.JButton btnLichSu;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnPotato;
    private javax.swing.JButton btnTaoDon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelTongTien;
    private javax.swing.JPanel panelContainerBurger;
    private javax.swing.JPanel panelContainerCream;
    private javax.swing.JPanel panelContainerDrink;
    private javax.swing.JPanel panelContainerPotato;
    private javax.swing.JPanel tabBurger;
    private javax.swing.JPanel tabCream;
    private javax.swing.JPanel tabDrink;
    private javax.swing.JPanel tabLichSu;
    private javax.swing.JPanel tabPotato;
    private javax.swing.JPanel tabTaoDonHang;
    private javax.swing.JTabbedPane tabbedTong;
    private javax.swing.JTable tblDonHang;
    private javax.swing.JTabbedPane tbpSub;
    // End of variables declaration//GEN-END:variables

}
